### ISSUE TITLE
Unicode tree icons highlighted wrong after 'oneline'

### ISSUE THREAD

**Issue by wilywampa** [Shougo/vimfiler.vim#266]
Syntax highlighting stopped working after 746e8e1. For example I use `let g:vimfiler_tree_closed_icon='▶'` which changed from
![screen shot 2015-03-18 at 7 18 02 pm](https://cloud.githubusercontent.com/assets/4472522/6723334/ac4928d0-cda3-11e4-9439-b7da0024e562.png)
to
![screen shot 2015-03-18 at 7 17 45 pm](https://cloud.githubusercontent.com/assets/4472522/6723337/bd97c90c-cda3-11e4-8d7a-170b09c5814f.png)
I tracked it down to unicode characters not being matched by `.` when using `\%123` in a pattern in the NFA regex engine. Choosing the old regex engine using `\%#=1` fixes the problem.

**Comment by Shougo** [comment]
Unfortunatelly, your Vim is old.
It is fixed in Vim 7.4.651.

**Comment by iansinnott** [comment]
This still appears to be a problem with MacVim as the latest snapshot available on github only includes patches up to 622
![screen shot 2015-03-21 at 9 04 57 pm](https://cloud.githubusercontent.com/assets/3154865/6767990/00dcabbc-d00e-11e4-9566-ff5c9b28cb82.png)

**Comment by wilywampa** [comment]
Don't merge my pull request in any case. There were still display issues with it anyway.
