### ISSUE TITLE
Error on opening file after using diff

### ISSUE THREAD

**Issue by itchyny** [Shougo/vimfiler.vim#304]
vimrc
```vim
set nocompatible
filetype off
set rtp+=/path/to/vimfiler
set rtp+=/path/to/unite
filetype plugin on
syntax enable
```

How to reproduce the problem
```
 $ touch test test2; vim -u vimrc -c "e test" -c "diffthis" -c "vnew test2" -c "diffthis"
:VimFiler
/test2
e
```

Error
```
Error detected while processing function vimfiler#mappings#do_switch_action:
line    9:
E749: empty buffer
```

**Comment by Shougo** [comment]
Fixed.

**Comment by itchyny** [comment]
The problem persists when I have the following configuration in the above minimal vimrc.
```vim
let g:vimfiler_restore_alternate_file = 0
```

**Comment by Shougo** [comment]
Unfortunatelly, it is feature.
Please disable the diff mode.
It displays Vim.  I cannot fix it.

**Comment by Shougo** [comment]
The message is printed if you just selected the buffer.
I think you should report the problem in vim_dev.

**Comment by itchyny** [comment]
Thank you for your suggestion. I've reported the bug to vim_dev. Thanks. https://groups.google.com/d/msg/vim_dev/pUhcNbcb2eQ/VrKSeT-DeB8J

**Comment by itchyny** [comment]
This bug is fixed in 7.4.810.
https://groups.google.com/d/msg/vim_dev/EtiZ5aom3zQ/7YPU2EpxHAAJ

**Comment by Shougo** [comment]
Thanks.
