### ISSUE TITLE
statusline becomes empty after "choose"

### ISSUE THREAD

**Issue by blyoa** [Shougo/vimfiler.vim#348]
I have encountered #264 since 1b7786991e22b437a5319187291eddbc77c9007b.
The commit might bring regression.

* Environment Information

 * OS: Windows 10 64bit
 * Vim version: 7.4.884 (modified by kaoriya) 64 bit

* Minimal vimrc 

```VimL
if has('vim_starting')
    set runtimepath+=~/.vim/bundle/unite.vim
    set runtimepath+=~/.vim/bundle/vimfiler
    set runtimepath+=~/.vim/bundle/vimproc.vim
endif
```

* Reproducible ways from Vim starting
 0. startup Vim
 1. split window (:split or :vsplit)
 2. execute VimFilerExplorer (:VimFilerExplorer)
 3. choose a file
 4. press enter
 5. choose window
 6. all statuslines are cleared except the statusline of chosen window

**Comment by Shougo** [comment]
Fixed.

**Comment by blyoa** [comment]
I think this issue isn't fixed. I updated vimfiler.vim to a46cca1445ca9687b77dc900cef6af3b3861a0fd, but this issue is still occurring.

**Comment by Shougo** [comment]
Fixed again.
