### ISSUE TITLE
Can't open directory in explorer mode as default

### ISSUE THREAD

**Issue by JohnnyNiu** [Shougo/vimfiler.vim#400]
Hi When I open a directory like:
```
vim ~/documents/
```

I want it open as explorer mode, but it gave me the view of single colume, then I need to run `:VimFilerExplorer` again to enter explorer mode.  How can I enter explorer mode as default? 

My config is below:
```
Plugin 'shougo/vimfiler.vim'
call vimfiler#custom#profile('default', 'context', {
            \ 'split': 1,
            \ 'winwidth' : 40,
            \ 'no_quit': 1,
            \ 'explorer': 1
            \ })

:let g:vimfiler_as_default_explorer = 1  " set vimfiler as default file exporer
```

Thanks

**Comment by Shougo** [comment]
Fixed.

**Comment by JohnnyNiu** [comment]
Such a quick feedback. Thank you very much @Shougo

**Comment by ld-prj** [comment]
Hey Shougo,

I'm still experiencing the same issue as JhonnyNiu.
I've copied his config into my `.vimrc` but it's not working.. Thoughts?

**Comment by ld-prj** [comment]
I've just updated and the command ` cd ~/Documents/ ` now has the split window, but still isn't in explorer mode (only shows current directory at a time - see screenshot). Heres whats in my `.vimrc`:
```
call plug#begin(~/.vim/plugged)
...
Plug 'shougo/vimfiler.vim'
...
call plug#end()

call vimfiler#custom#profile('default', 'context', {
            \ 'split': 1,
            \ 'winwidth' : 40,
            \ 'no_quit': 1,
            \ 'explorer': 1
            \ })
:let g:vimfiler_as_default_explorer = 1  " set vimfiler as default file exporer
```
![image](https://user-images.githubusercontent.com/29705680/30569383-f3b42f48-9d1d-11e7-8e36-044f3bea6e04.png)

**Comment by Shougo** [comment]
> I've just updated and the command cd ~/Documents/ now has the split window, but still isn't in explorer mode (only shows current directory at a time - see screenshot).

I don't understand.  It works properly.
We have not ESP skill.
Please explain the problem more clearly.

**Comment by Shougo** [comment]
> (only shows current directory at a time - see screenshot)

I have see the screenshot.
It is the explorer mode.

**Comment by ld-prj** [comment]
Ah shit my bad, before the explorer would only display the directory and not show the whole tree, but it is now working. Thanks for the quick reply and sorry for the confusion!

**Comment by Shougo** [comment]
OK.
